CREATE DATABASE olist_project;
USE olist_project;

CREATE TABLE customers (
    customer_id VARCHAR(50) PRIMARY KEY,
    customer_unique_id VARCHAR(50),
    customer_zip_code_prefix INT,
    customer_city VARCHAR(100),
    customer_state VARCHAR(2)
);

CREATE TABLE orders (
    order_id VARCHAR(50) PRIMARY KEY,
    customer_id VARCHAR(50),
    order_status VARCHAR(20),
    order_purchase_timestamp DATETIME,
    order_approved_at DATETIME,
    order_delivered_carrier_date DATETIME,
    order_delivered_customer_date DATETIME,
    order_estimated_delivery_date DATETIME
);

CREATE TABLE order_items (
    order_id VARCHAR(50),
    order_item_id INT,
    product_id VARCHAR(50),
    seller_id VARCHAR(50),
    shipping_limit_date DATETIME,
    price DECIMAL(10, 2),
    freight_value DECIMAL(10, 2),
    PRIMARY KEY (order_id, order_item_id)
);

SELECT *
FROM customers;

SELECT COUNT(*)
FROM customers;

TRUNCATE TABLE  customers;

-- Replace 'YourName' with your actual computer username
-- Replace 'YourName' with your actual computer username
SET GLOBAL local_infile = 1;

LOAD DATA LOCAL INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/olist_customers_dataset.csv'
INTO TABLE customers
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


select * 
FROM orders;
SHOW VARIABLES LIKE 'secure_file_priv';

-- check for duplicates
SELECT customer_id, COUNT(*)
FROM customers
GROUP BY customer_id
HAVING COUNT(*) > 1;

SELECT *
FROM customers

UPDATE customers
SET customer_city = UPPER(customer_city);

-- CHECK FOR NULLS
SELECT *
FROM customers
WHERE customer_zip_code_prefix IS NULL OR customer_city IS NULL OR customer_state IS NULL;

-- TO SEE OUR TOP CUSTOMERS
SELECT customer_unique_id,COUNT(*) AS order_count
FROM customers
GROUP BY customer_unique_id
HAVING order_count > 1
ORDER BY order_count DESC;

-- orders that arrive after they were promised
SELECT *
FROM orders
WHERE order_delivered_customer_date > order_estimated_delivery_date;

-- to see orders that havent been delivered
SELECT order_status, order_delivered_customer_date
FROM orders
WHERE order_delivered_customer_date IS NULL
GROUP BY order_status, order_delivered_customer_date;

SELECT order_id, COUNT(*)
FROM order_items
GROUP BY order_id
HAVING COUNT(*) > 1;

SELECT *
FROM order_items 
WHERE price = 0 OR freight_value < 0;


-- 20. PROPER ANALYSIS QUESTIONS TO PROVIDE INSIGHTS INTO THE SALES
-- 1. TOTAL SALES WHAT IS THE TOTAL REVENUE GENERATED BY THE BUSINESS
SELECT ROUND(SUM(price + freight_value), 2) AS Total_revenue
FROM ORDER_ITEMS;

-- 2. ORDER VOLUME: HOW MANY ORDERS ARE PLACED EACH MONTH
SELECT order_id, COUNT(*) AS ordercount , (MONTHNAME (`order_purchase_timestamp`)) AS `MONTH`
FROM orders
GROUP BY order_id, `MONTH`;


-- 3. POPULAR CATEGORIES: WHICH PRODUCT CATEGORIES HAVE THE HIGHEST NUMBER OF ORDERS
SELECT product_id, COUNT(*) AS pdt_count
FROM order_items
GROUP BY product_id
ORDER BY pdt_count DESC
LIMIT 5;

-- 4. CUSTOMER LOCATION : WHICH 10 CITIES HAVE THE MOST CUSTOMER
SELECT  customer_city, COUNT(customer_unique_id) AS each_customer
FROM customers
GROUP BY customer_city
ORDER BY each_customer DESC
LIMIT 10;

-- 5. AVERAGE ORDER VALUE: ON AVERAGE HOW MUCH DOES A CUSTOMER SPEND PER TRANSACTIOB
SELECT ROUND(avg(price), 2)
FROM order_items;

-- 6. WHAT PERCENTAGE OF ORDERS ARE ACTUALLY DELIVERED
SELECT 
SUM(CASE
WHEN order_status = 'delivered' THEN 1
ELSE 0 END)/
NULLIF(COUNT(*), 0) AS PCT_delivered
FROM orders;

-- 7. SHIPPING IMPACT BY STATE: WHICH STATES ARE MOST EXPENSIVE TO SHIP TO
SELECT customer_state, AVG(freight_value) AS avg_shipping_cost
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items i ON o.order_id = i.order_id
GROUP BY customer_state
ORDER BY avg_shipping_cost DESC;

-- 8. DELIVERY PERFORMANCE: WHAT IS THE AVERAGE DIFFERENCE BEYWEEN THE ESTIMATED DELIVERY DATE
-- AND ACTUAL DELIVERY DATE DATEDIFF() CALCULATES DIFFERENCE BETWEEN 2 DATES
SELECT order_estimated_delivery_date, order_delivered_customer_date, 
AVG(DATEDIFF(order_estimated_delivery_date, order_delivered_customer_date)) AS Delivery_performance
FROM ORDERS
GROUP BY order_estimated_delivery_date, order_delivered_customer_date;

-- 9. PEAK SHOPPINH HOUR: WHAT HOUR OF THE DAY IS RUSH HOUR
SELECT order_id, COUNT(*) AS order_count, HOUR(`order_purchase_timestamp`) AS purchase_hour
FROM orders
GROUP BY order_id, purchase_hour
ORDER BY order_count DESC

-- 10. TOP SELLERS BY REVENUE: WHICH SELLERS ARE MAKING THE MOST MONEY
SELECT seller_id, SUM(price) AS total_sales
FROM order_items
GROUP BY seller_id
ORDER BY total_sales DESC;

-- 11. CUSTOMER PURCHASE BEHAVIOUR: IDENTIFY THE FIRST AND LAST PURCHASE FOR EVERY UNIQUE CUSTOMER
WITH customer_purchase_behaviour AS
(SELECT customer_unique_id, order_purchase_timestamp
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id)

SELECT customer_unique_id, MIN(order_purchase_timestamp), MAX(order_purchase_timestamp)
FROM customer_purchase_behaviour
GROUP BY customer_unique_id;

-- 12. TOP SPENDERS PER STATE: RANK THE TOP 3 CUSTOMERS IN EACH STATE BASED ON THEIR TOTAL SPEND
SELECT * FROM
(SELECT c.customer_unique_id, customer_state, SUM(price) AS total_spend,
RANK() OVER(PARTITION BY customer_state ORDER BY SUM(price) DESC) AS customer_rank
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items i ON o.order_id = i.order_id
GROUP BY customer_unique_id, customer_state) AS T

WHERE customer_rank <= 3;

-- 13. CUMULATIVE REVENUE: CALCULATE THE RUNNING TOTAL OF REVENUE DAY-BY-DAY FOR THE YEAR 2017
WITH Running_total AS
(SELECT SUM(price) AS daily_revenue, SUBSTRING(`order_purchase_timestamp`, 9,2) AS `Day`
FROM order_items i
JOIN orders o ON i.order_id = o.order_id
WHERE SUBSTRING(`order_purchase_timestamp`, 9,2) IS NOT NULL
GROUP BY `Day`)
-- NOW TO DO THE RUNNING SUN
SELECT `Day`, daily_revenue, SUM(daily_revenue) OVER(ORDER BY `Day`) AS running_t
FROM Running_total

-- cleaner method for num ber 13

WITH DailyRevenue AS (
SELECT
-- This creates the "Monday 01 January" format
DATE_FORMAT(o.order_purchase_timestamp, '%W %d %M') AS formatted_date,
-- We keep the raw date so SQL knows how to put them in order
DATE(o.order_purchase_timestamp) AS raw_date,
SUM(oi.price) AS daily_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
-- Filter for the year 2017
WHERE o.order_purchase_timestamp >= '2017-01-01'
AND o.order_purchase_timestamp <= '2017-12-31'
GROUP BY raw_date, formatted_date
)
SELECT
formatted_date,
daily_revenue,
SUM(daily_revenue) OVER(ORDER BY raw_date) AS running_total
FROM DailyRevenue
ORDER BY raw_date;

-- 14. ORDER ITEM CONCENTRATION: FIND THE PCT CONTRBUTION OF EACH INDIVIDUAL ORDER ITEM TO ITS TOTAL ORDER VALUE
SELECT order_id, price, SUM(price + freight_value) OVER(PARTITION BY order_id) AS total_order_value,
(price/SUM(price + freight_value) OVER(PARTITION BY order_id)) * 100 item_pct
FROM order_items;

-- 15. RETENTION LAG: (WINDOWS FUNCTION) FOR REPEAT CUSTOMERS CALCULATE THE NUMBER OF DAYS BETWEEN THEIR FIRST
-- AND SECOND ORDER lag is oly fumction for looking bk to compare rows in the same column
WITH order_seq AS
(SELECT customer_unique_id, order_purchase_timestamp, LAG(order_purchase_timestamp)
OVER(PARTITION BY customer_unique_id ORDER BY order_purchase_timestamp) AS prev_order
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id)

SELECT customer_unique_id, DATEDIFF(order_purchase_timestamp, prev_order) AS days_btw
FROM order_seq
WHERE prev_order IS NOT NULL;

-- 16. HIGH VALUE STATES CTE: FIND STATES WHERE AVERAGE ORDER VALUE IS HIGHER THAN OVERALL 
-- AVERAGE ORDER VALUE OF ENTIRE COMPANY
WITH StateAOV AS
(SELECT customer_state, AVG(price) AS avg_order_value_state
FROM customers c 
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items i ON o.order_id = i.order_id
GROUP BY customer_state)

SELECT *
FROM StateAOV
WHERE avg_order_value_state > (SELECT AVG(price) FROM order_items);

-- 17. SHIPPING EFFICIENCY: IDENTIFY ORDERS THAT TOOK LONGER THAN THE AVERAGE SHIPPING TIME FOR 
-- THEIR SPECIFIC DELIVERY STATE

SELECT
order_id,
customer_state,
actual_shipping_time,
avg_state_shipping
FROM (
SELECT
o.order_id,
c.customer_state,
DATEDIFF(o.order_delivered_customer_date, o.order_delivered_carrier_date) AS actual_shipping_time,
AVG(DATEDIFF(o.order_delivered_customer_date, o.order_delivered_carrier_date)) OVER(PARTITION BY c.customer_state) AS avg_state_shipping
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
WHERE o.order_delivered_customer_date IS NOT NULL
) AS shipping_stats
WHERE actual_shipping_time > avg_state_shipping;


-- 18.  MONTHLY SELLER PERFORMANCE: CALCULATE THE MONTH OVER MONTH GROWTH IN REVENUE FOR THE TOP PERFORMING SELLER
WITH SellerMonthly AS (
SELECT
seller_id,
DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
SUM(oi.price) AS revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE seller_id = 'seller_id_here' -- Replace with a top seller ID
GROUP BY seller_id, month
)
SELECT
month,
revenue,
LAG(revenue) OVER(ORDER BY month) AS prev_month_revenue,
(revenue - LAG(revenue) OVER(ORDER BY month)) / LAG(revenue) OVER(ORDER BY month) * 100 AS growth_pct
FROM SellerMonthly;
